### ISSUE TITLE
Non-ASCII character '\xc2' in node.py

### ISSUE THREAD

**Issue by rwl** [oxfordcontrol/miosqp#2]
I receive this error when using `miosqp` with Python 2.7:

```
SyntaxError: Non-ASCII character '\xc2' in file miosqp/node.py on line 17, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

https://github.com/oxfordcontrol/miosqp/blob/e15c5aa5be2674fea5c850d1bf969769ae310dbc/miosqp/node.py#L16

**Comment by bstellato** [comment]
That was a typo. Fixed in this commit ba02ad6e7c6d2bf0282f1abfe8c7671446beb86b. Thanks for spotting it.
